src/Database/Domain/Entity/Commerce/Order/Coupon.php
<?php

namespace App\Database\Domain\Entity\Commerce\Order;

use App\Database\Domain\Entity\AbstractEntity;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @author Anton Zakharuk <zahaton01@gmail.com>
 *
 * Research & Development
 *
 * @ORM\Entity(repositoryClass="App\Database\Domain\Repository\Commerce\Order\CouponRepository")
 *
 * @UniqueEntity(fields={"code"}, message="Coupon already exists")
 */
class Coupon extends AbstractEntity
{
    public const TYPE_PERCENT = 'coupon_percent';
    public const TYPE_FIXED   = 'coupon_fixed';

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=false, unique=true)
     *
     * @Assert\NotNull()
     * @Assert\NotBlank()
     */
    private $code;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=false)
     *
     * @Assert\NotBlank(message="Coupon discount type cannot be blank")
     * @Assert\NotNull(message="Coupon discount type cannot be null")
     * @Assert\Choice(choices={Coupon::TYPE_PERCENT, Coupon::TYPE_FIXED}, message="Invalid discount type")
     */
    private $discountType;

    /**
     * @var float
     *
     * @ORM\Column(type="float", nullable=true)
     */
    private $discountPercent;

    /**
     * @var float
     *
     * @ORM\Column(type="float", nullable=true)
     */
    private $discountFixed;

    /**
     * @return string
     */
    public function getCode(): ?string
    {
        return $this->code;
    }

    /**
     * @param string $code
     *
     * @return self
     */
    public function setCode(?string $code): self
    {
        $this->code = $code;
        return $this;
    }

    /**
     * @return string
     */
    public function getDiscountType(): ?string
    {
        return $this->discountType;
    }

    /**
     * @param string $discountType
     *
     * @return self
     */
    public function setDiscountType(?string $discountType): self
    {
        $this->discountType = $discountType;
        return $this;
    }

    /**
     * @return float
     */
    public function getDiscountPercent(): ?float
    {
        return $this->discountPercent;
    }

    /**
     * @param float $discountPercent
     *
     * @return self
     */
    public function setDiscountPercent(?float $discountPercent): self
    {
        $this->discountPercent = $discountPercent;
        return $this;
    }

    /**
     * @return float
     */
    public function getDiscountFixed(): ?float
    {
        return $this->discountFixed;
    }

    /**
     * @param float $discountFixed
     *
     * @return self
     */
    public function setDiscountFixed(?float $discountFixed): self
    {
        $this->discountFixed = $discountFixed;
        return $this;
    }

    /**
     * @return bool
     */
    public function isFixed()
    {
        return $this->discountType === self::TYPE_FIXED;
    }

    /**
     * @return bool
     */
    public function isPercent()
    {
        return $this->discountType === self::TYPE_PERCENT;
    }
}

src/Database/Domain/Entity/Commerce/Order/Courier.php
<?php

namespace App\Database\Domain\Entity\Commerce\Order;

use App\Database\Domain\Entity\AbstractEntity;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\PersistentCollection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @author Anton Zakharuk <zahaton01@gmail.com>
 *
 * Research & Development
 *
 * @ORM\Entity(repositoryClass="App\Database\Domain\Repository\Commerce\Order\CourierRepository")
 */
class Courier extends AbstractEntity
{
    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", nullable=false)
     *
     * @Assert\NotBlank(message="Courier name cannot be empty")
     * @Assert\NotNull(message="Courier name cannot be null")
     */
    private $name;

    /**
     * @var PersistentCollection|Order[]
     *
     * @ORM\ManyToMany(targetEntity=Order::class, mappedBy="couriers")
     * @ORM\JoinTable(name="order_couriers",
     *    joinColumns={@ORM\JoinColumn(name="order_id", referencedColumnName="id", onDelete="CASCADE")},
     *    inverseJoinColumns={@ORM\JoinColumn(name="courier_id", referencedColumnName="id", onDelete="CASCADE")}
     * )
     */
    private $orders;

    /**
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     *
     * @return self
     */
    public function setName(?string $name): self
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return PersistentCollection|Order[]
     */
    public function getOrders(): ?PersistentCollection
    {
        return $this->orders;
    }

    /**
     * @param Order $order
     *
     * @return $this
     */
    public function addOrder(Order $order)
    {
        $this->orders[] = $order;

        return $this;
    }
}

src/Database/Domain/Entity/Commerce/Product/AbstractProductCategory.php
<?php

namespace App\Database\Domain\Entity\Commerce\Product;

use App\Database\Domain\Entity\AbstractEntity;
use App\Database\Domain\Traits\SlugTrait;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @author Anton Zakharuk <zahaton01@gmail.com>
 *
 * Research & Development
 *
 * @ORM\MappedSuperclass()
 */
abstract class AbstractProductCategory extends AbstractEntity
{
    use SlugTrait;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=false)
     *
     * @Assert\NotBlank(message="Product category name cannot be empty")
     * @Assert\NotNull(message="Product category name cannot be empty")
     */
    protected $name;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    protected $description;

    /**
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     *
     * @return self
     */
    public function setName(string $name): self
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return string
     */
    public function getDescription(): ?string
    {
        return html_entity_decode($this->description);
    }

    /**
     * @param string $desc
     *
     * @return self
     */
    public function setDescription(?string $desc): self
    {
        $this->description = $desc;
        return $this;
    }
}

src/Database/Domain/Entity/Commerce/Product/Category/Meta/ProductCategoryMeta.php
<?php

namespace App\Database\Domain\Entity\Commerce\Product\Category\Meta;

use App\Database\Domain\Entity\AbstractMeta;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\PersistentCollection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @author Anton Zakharuk <zahaton01@gmail.com>
 *
 * Research & Development
 *
 * @ORM\Entity()
 */
class ProductCategoryMeta extends AbstractMeta
{
    /**
     * @var PersistentCollection|ProductCategoryMetaTranslation[]
     *
     * @ORM\OneToMany(targetEntity=ProductCategoryMetaTranslation::class, mappedBy="meta", cascade={"persist", "remove"})
     */
    private $translations;

    /**
     * @return ProductCategoryMetaTranslation[]|PersistentCollection
     */
    public function getTranslations()
    {
        return $this->translations;
    }

    /**
     * @param ProductCategoryMetaTranslation[]|PersistentCollection $translations
     *
     * @return self
     */
    public function setTranslations($translations): self
    {
        $this->translations = $translations;
        return $this;
    }
}

src/Database/Domain/Entity/Commerce/Product/Product.php
<?php

namespace App\Database\Domain\Entity\Commerce\Product;

use App\Application\Util\Identifier;
use App\Database\Domain\Entity\AbstractEntity;
use App\Database\Domain\Entity\Commerce\Product\Category\ProductCategory;
use App\Database\Domain\Entity\Commerce\Product\Media\ProductMedia;
use App\Database\Domain\Entity\Commerce\Product\Meta\ProductMeta;
use App\Database\Domain\Entity\Commerce\Product\Specification\ProductSpecification;
use App\Database\Domain\Entity\Commerce\Product\SubCategory\ProductSubCategory;
use App\Database\Domain\Entity\Commerce\Product\Variety\ProductVariety;
use App\Database\Domain\Traits\CreationDateTrait;
use App\Database\Domain\Traits\SlugTrait;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\PersistentCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @author Anton Zakharuk <zahaton01@gmail.com>
 *
 * Research & Development
 *
 * @ORM\Entity(repositoryClass="App\Database\Domain\Repository\Commerce\Product\ProductRepository")
 *
 * @UniqueEntity(fields={"vendorCode"}, message="Product with such vendor code already exists")
 */
class Product extends AbstractEntity
{
    use SlugTrait;
    use CreationDateTrait;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=false)
     *
     * @Assert\NotNull(message="Product name cannot be empty")
     * @Assert\NotBlank(message="Product name cannot be empty")
     */
    private $name;

    /**
     * @var ProductMedia
     *
     * @ORM\OneToOne(targetEntity=ProductMedia::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="media_id", referencedColumnName="id")
     *
     * @Assert\Valid()
     */
    private $media;

    /**
     * @var ProductMeta
     *
     * @ORM\OneToOne(targetEntity=ProductMeta::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="meta_id", referencedColumnName="id")
     *
     * @Assert\Valid()
     */
    private $meta;

    /**
     * @var PersistentCollection|ProductVariety[]
     *
     * @ORM\OneToMany(targetEntity=ProductVariety::class, mappedBy="product")
     */
    private $varieties;

    /**
     * @var PersistentCollection|ProductTranslation[]
     *
     * @ORM\OneToMany(targetEntity="ProductTranslation", mappedBy="product", cascade={"persist", "remove"})
     */
    private $translations;

    /**
     * @var ProductCategory
     *
     * @ORM\ManyToOne(targetEntity=ProductCategory::class, inversedBy="products", cascade={"persist"})
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id", onDelete="SET NULL")
     *
     * @Assert\Valid()
     */
    private $productCategory;

    /**
     * @var ProductSubCategory
     *
     * @ORM\ManyToOne(targetEntity=ProductSubCategory::class, inversedBy="products")
     * @ORM\JoinColumn(name="sub_category_id", referencedColumnName="id")
     *
     * @Assert\Valid()
     */
    private $productSubCategory;

    /**
     * @var PersistentCollection|ProductSpecification[]
     *
     * @ORM\OneToMany(targetEntity=ProductSpecification::class, mappedBy="product", cascade={"persist", "remove"})
     */
    private $specifications;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", nullable=false)
     *
     * @Assert\NotNull(message="Product visibility status cannot be empty")
     */
    private $isVisible;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @var float
     *
     * @ORM\Column(type="float", nullable=true)
     */
    private $price;

    /**
     * @var ProductPromo
     *
     * @ORM\OneToOne(targetEntity="ProductPromo", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="promo_id", referencedColumnName="id")
     *
     * @Assert\Valid()
     */
    private $promo;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true, unique=true)
     */
    private $vendorCode;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=false)
     *
     * @Assert\NotNull(message="Product availability status cannot be empty")
     * @Assert\NotBlank(message="Product availability status cannot be empty")
     */
    private $availability;

    public function __clone()
    {
        $this->id             = Identifier::uuid();
        $this->vendorCode     = uniqid();
        $this->meta           = clone $this->meta;
        $this->media          = clone $this->media;
        $this->promo          = clone $this->promo;
        $this->translations   = [];
        $this->varieties      = [];
        $this->specifications = [];
    }

    /**
     * @return string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     *
     * @return self
     */
    public function setName(string $name): self
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return ProductMedia
     */
    public function getMedia(): ProductMedia
    {
        return $this->media;
    }

    /**
     * @param ProductMedia $media
     *
     * @return self
     */
    public function setMedia(ProductMedia $media): self
    {
        $this->media = $media;
        return $this;
    }

    /**
     * @return ProductMeta
     */
    public function getMeta(): ProductMeta
    {
        return $this->meta;
    }

    /**
     * @param ProductMeta $meta
     *
     * @return self
     */
    public function setMeta(ProductMeta $meta): self
    {
        $this->meta = $meta;
        return $this;
    }

    /**
     * @return ProductVariety[]|PersistentCollection
     */
    public function getVarieties()
    {
        return $this->varieties;
    }

    /**
     * @param ProductVariety[]|PersistentCollection $varieties
     *
     * @return self
     */
    public function setVarieties($varieties): self
    {
        $this->varieties = $varieties;
        return $this;
    }

    /**
     * @return ProductTranslation[]|PersistentCollection
     */
    public function getTranslations()
    {
        return $this->translations;
    }

    /**
     * @param ProductTranslation[]|PersistentCollection $translations
     *
     * @return self
     */
    public function setTranslations($translations): self
    {
        $this->translations = $translations;
        return $this;
    }

    /**
     * @return ProductCategory
     */
    public function getProductCategory(): ?ProductCategory
    {
        return $this->productCategory;
    }

    /**
     * @param ProductCategory $productCategory
     *
     * @return self
     */
    public function setProductCategory(?ProductCategory $productCategory): self
    {
        $this->productCategory = $productCategory;
        return $this;
    }

    /**
     * @return ProductSubCategory
     */
    public function getProductSubCategory(): ?ProductSubCategory
    {
        return $this->productSubCategory;
    }

    /**
     * @param ProductSubCategory $productSubCategory
     *
     * @return self
     */
    public function setProductSubCategory(?ProductSubCategory $productSubCategory): self
    {
        $this->productSubCategory = $productSubCategory;
        return $this;
    }

    /**
     * @return ProductSpecification[]|PersistentCollection
     */
    public function getSpecifications()
    {
        return $this->specifications;
    }

    /**
     * @param ProductSpecification[]|PersistentCollection $specifications
     *
     * @return self
     */
    public function setSpecifications($specifications): self
    {
        $this->specifications = $specifications;
        return $this;
    }

    /**
     * @return bool
     */
    public function isVisible(): bool
    {
        return $this->isVisible;
    }

    /**
     * @param bool $isVisible
     *
     * @return self
     */
    public function setIsVisible(bool $isVisible): self
    {
        $this->isVisible = $isVisible;
        return $this;
    }

    /**
     * @return string
     */
    public function getDescription(): ?string
    {
        return html_entity_decode($this->description);
    }

    /**
     * @param string $desc
     *
     * @return self
     */
    public function setDescription(?string $desc): self
    {
        $this->description = $desc;
        return $this;
    }

    /**
     * @return float
     */
    public function getPrice(): ?float
    {
        return $this->price;
    }

    /**
     * @param float $price
     *
     * @return self
     */
    public function setPrice(float $price): self
    {
        $this->price = $price;
        return $this;
    }

    /**
     * @return ProductPromo
     */
    public function getPromo(): ProductPromo
    {
        return $this->promo;
    }

    /**
     * @param ProductPromo $promo
     *
     * @return self
     */
    public function setPromo(ProductPromo $promo): self
    {
        $this->promo = $promo;
        return $this;
    }

    /**
     * @return string
     */
    public function getVendorCode(): ?string
    {
        return $this->vendorCode;
    }

    /**
     * @param string $vendorCode
     *
     * @return self
     */
    public function setVendorCode(string $vendorCode): self
    {
        $this->vendorCode = $vendorCode;
        return $this;
    }

    /**
     * @return string
     */
    public function getAvailability(): string
    {
        return $this->availability;
    }

    /**
     * @param string $availability
     *
     * @return self
     */
    public function setAvailability(string $availability): self
    {
        $this->availability = $availability;
        return $this;
    }

    /**
     * @return float|null
     */
    public function getRealPrice()
    {
        if ($this->getPromo()->isSaleStatus()) {
            return $this->getPromo()->getSalePrice();
        }

        return $this->price;
    }

    /**
     * @param ProductSpecification $specification

templates/site/themes/default/pages/commerce/cart/index.html.twig
{% extends 'site/themes/default/site_layout.html.twig' %}

{% block title %}{{ services.translator.trans(page.meta, 'pageTitle') }}{% endblock %}
{% block metaDescription %}{{ services.translator.trans(page.meta, 'metaDesc') }}{% endblock %}
{% block metaTitle %}{{ services.translator.trans(page.meta, 'metaTitle') }}{% endblock %}
{% block metaKeywords %}{{ services.translator.trans(page.meta, 'metaKeywords') }}{% endblock %}

{% block content %}
    <div class="container mt-220">
        <h3>{{ 'Cart'|trans }}</h3>
    </div>
    <div class="container mt-50 mb-120" style="min-height: 500px">
        <div class="cart-title">
            <div class="row">
                <div class="col-md-4">
                    <h6 class="ml-15">{{ 'Product'|trans }}</h6>
                </div>
                <div class="col-md-2">
                    <h6>{{ 'Price'|trans }}</h6>
                </div>
                <div class="col-md-2">
                    <h6>{{ 'Quantity'|trans }}</h6>
                </div>
                <div class="col-md-2">
                    <h6>{{ 'Variety'|trans }}</h6>
                </div>
                <div class="col-md-2">
                    <h6>{{ 'Sum'|trans }}</h6>
                </div>
            </div>
        </div>
        {% set currency = services.globals.get('currency') %}
        {% for cartProduct in cart.cartProducts %}
            {% set product = cartProduct.relatedProduct %}
            <div class="cart-single-item">
                <div class="row align-items-center">
                    <div class="col-md-4 col-sm-12 col-12 mt-20">
                        <div class="product-item d-flex align-items-center">
                            <img width="128px" height="128px" src="{{ asset(services.media.product.pic(product)) }}" class="img-fluid"
                                 alt="{{ services.translator.trans(product, 'name') }}">
                            <h6>{{ services.translator.trans(product, 'name') }}</h6>
                        </div>
                    </div>
                    <div class="col-md-2 col-sm-6 col-6 mt-20">
                        <div class="price">{{ product.realPrice|number_format(2, '.', '') }} {{ currency|trans }}</div>
                    </div>
                    <div class="col-md-2 col-sm-6 col-6 mt-20">
                        <div class="quantity-container d-flex align-items-center mt-15">
                            <input data-price="{{ product.realPrice }}" data-id="{{ product.id }}" type="text"
                                   class="quantity-amount" value="{{ cartProduct.quantity }}"/>
                            <div class="arrow-btn d-inline-flex flex-column">
                                <button data-id="{{ product.id }}" class="increase arrow" type="button"
                                        title="Increase Quantity"><span class="lnr lnr-chevron-up"></span></button>
                                <button data-id="{{ product.id }}" class="decrease arrow" type="button"
                                        title="Decrease Quantity"><span class="lnr lnr-chevron-down"></span></button>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-2 col-sm-12 col-12 mt-20">
                        <ul class="js-varieties-ul" data-id="{{ product.id }}">
                            {% for productVariety in product.varieties %}
                                <li class="col-lg-12 mt-10">
                                    <h6>{{ services.translator.trans(productVariety.variety, 'name') }}</h6>
                                    <div class="mt-10">
                                        <select class="js-variety form-control custom-select"
                                                data-id="{{ productVariety.variety.id }}">
                                            {% for productVarietyValue in productVariety.values %}
                                                {% if productVarietyValue.availability == constant('App\\Database\\Domain\\Model\\EntityState\\Availability::AVAILABLE') %}
                                                    <option
                                                            {% for cartVariety in cartProduct.varieties %}
                                                                {% if productVarietyValue.attachedValue.id == cartVariety.relatedValue.id %} selected {% endif %}
                                                            {% endfor %}
                                                            value="{{ productVarietyValue.attachedValue.id }}">{{ services.translator.trans(productVarietyValue.attachedValue, 'value') }}
                                                    </option>
                                                {% else %}
                                                    <option value="{{ productVarietyValue.attachedValue.id }}"
                                                            disabled>{{ services.translator.trans(productVarietyValue.attachedValue, 'value') }}
                                                        ({{ productVarietyValue.availability|trans }})
                                                    </option>
                                                {% endif %}
                                            {% endfor %}
                                        </select>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="col-md-2 col-sm-12 col-12 mt-20">
                        <div data-id="{{ product.id }}" class="total js-total-price"
                             id="js-total-{{ product.id }}">{{ cartProduct.totalPrice|number_format(2, '.', '') }} {{ currency|trans }}</div>
                    </div>
                    <div class="col-md-2 col-sm-12 col-12 mt-20">
                        <div class="total">
                            <a href="{{ path('site_cart_remove_product', {'id': product.id}) }}"
                               class="view-btn color-2 mt-10"><span>{{ 'Remove'|trans }}</span></a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="subtotal-area d-flex align-items-center justify-content-end">
            <div class="title text-uppercase">{{ 'Total'|trans }}</div>
            <div class="subtotal"
                 id="subTotal">{{ cart.totalPrice|number_format(2, '.', '') }} {{ currency|trans }}</div>
        </div>
        <div id="errHolder" style="display: none" class="alert alert-danger">

        </div>
        <div class="row justify-content-end" style="margin-bottom: 50px">
            <button class="view-btn color-2 mt-10" id="finish"><span>{{ 'Checkout'|trans }}</span></button>
        </div>
    </div>

    <script>
        const REFILL_CART_URL       = '{{ path('ajax_cart_refill') }}';
        const CURRENCY              = '{{ currency|trans }}';
        const TEXT_NO_ITEMS_IN_CART = '{{ 'You did not add any items to cart'|trans }}';
        const ORDER_URL             = '{{ path('site_order_index') }}';
    </script>
{% endblock %}

{% block js %}
    <script src="{{ asset('assets/site/themes/default/js/numeral.min.js') }}"></script>
    <script src="{{ asset('assets/site/themes/default/includes/js/cart.js') }}"></script>
{% endblock %}